# Generated by Django 4.2 on 2023-05-20 22:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('time_limit', models.IntegerField()),
                ('memory_limit', models.IntegerField()),
                ('input_file', models.FileField(upload_to='input_files/')),
                ('output_file', models.FileField(upload_to='output_files/')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=10)),
                ('code', models.TextField()),
                ('compilation_error', models.TextField(blank=True, null=True)),
                ('execution_error', models.TextField(blank=True, null=True)),
                ('output_file', models.FileField(blank=True, null=True, upload_to='')),
                ('result', models.CharField(blank=True, max_length=2, null=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.problem')),
            ],
        ),
    ]
